name: detox-butler-actions
on: [ push ]
jobs:
    build-and-test:
        name: build and test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 20
                  fetch-tags: true

            - run: echo "Setting up JDK"
            - name: set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'zulu'
                  cache: gradle
            - name: Build and lint
              run: ./gradlew lint test