name: detox-butler-actions
on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
    build-and-test:
        name: build and test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
                fetch-tags: true
            - run: echo "Setting up JDK"
            - name: set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'zulu'
                  cache: gradle
            - name: Build and lint
              run: ./gradlew lint test assembleRelease
    deploy:
      name: deploy
      needs: build-and-test
      if: startsWith(github.ref, 'refs/tags/')
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 1
            fetch-tags: true
        - run: echo "Setting up JDK"
        - name: set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'zulu'
            cache: gradle
        - name: Build Release APK
          run: ./gradlew assembleRelease
        - name: Deploy to GitHub Releases
          uses: ncipollo/release-action@v1
          with:
            artifacts: "app/build/outputs/apk/**/release/*.apk"
            draft: true
            generateReleaseNotes: true
            makeLatest: true